### ISSUE TITLE
how to use original vat in your project

### ISSUE THREAD

**Issue by superwars** [sndnyang/xvat#1]
how to use original vat in your project? There is no xi variable in args?

**Comment by sndnyang** [comment]
It didn't contain the original vat code~~~
Maybe I can create a new repo for the original VAT

**Comment by superwars** [comment]
Thanks!

**Comment by sndnyang** [comment]
https://github.com/sndnyang/vat_pytorch  this one.
It has mnist/cifar10/svhn scripts.
But if you need, you still need to tune the +entropy minimization.
